// Self-playing demo of the day-POC.
//
// Same UI as `npm run day` — mission card, per-turn coaching, NPC voice,
// Aoi in the meadow — but the "player" turns are generated by an AI
// student instead of typed by a human. Use this to show a friend what
// the loop feels like without making them know Japanese.
//
// Run with:
//   npm run day-demo
//   npm run day-demo -- --no-music
//   npm run day-demo -- --no-tts
//   npm run day-demo -- --player-voice Puck
//   npm run day-demo -- --pace 0.7        # 0.4 (fast) … 1.5 (slow)

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawn, type ChildProcess } from "node:child_process";
import { randomUUID } from "node:crypto";
import { stdin, stdout } from "node:process";
import "dotenv/config";

import { synthesizeSpeech } from "../src/lib/audio/tts.js";
import { GeminiClient } from "../src/lib/llm/client.js";

// ---------------------------------------------------------------------------
// Voices
// ---------------------------------------------------------------------------

const VOICE_BOOKSHOP = "Iapetus";
const VOICE_VENDOR = "Kore";
const VOICE_NARRATOR = "Algenib";
const DEFAULT_AOI_VOICE = "Leda";
const DEFAULT_PLAYER_VOICE = "Aoede"; // warm young-adult female — clearly "you"

const AOI_STYLE_PREFIX =
  "Speak softly, slowly, in the voice of a small, gentle, blind young girl. Almost a half-whisper. ";

const DEFAULT_TEXT_MODEL = "gemini-flash-latest";

// ---------------------------------------------------------------------------
// Beds
// ---------------------------------------------------------------------------

const DEFAULT_MEADOW_BED = "tmp/sample-minshuku.wav";
const BOOKSHOP_BED = "tmp/sample-bookshop.wav";
const MARKET_BED = "tmp/sample-cafe.wav";
const BED_VOLUME_ERRAND = "0.20";
const BED_VOLUME_MEADOW = "0.16";

// ---------------------------------------------------------------------------
// Errands (lifted from day-poc.ts)
// ---------------------------------------------------------------------------

interface ErrandStep {
  prompt: string;
  grammar: string;
  vocab: readonly { word: string; gloss: string }[];
  exampleJa: string;
}

interface ErrandConfig {
  id: string;
  label: string;
  bed: string;
  npcSpeaker: string;
  npcVoice: string;
  npcPersona: string;
  missionEn: string;
  missionJa: string;
  strategy: string;
  opener: string;
  steps: readonly ErrandStep[];
}

const ERRAND_BOOKSHOP: ErrandConfig = {
  id: "bookshop",
  label: "the quiet bookshop on the side street",
  bed: BOOKSHOP_BED,
  npcSpeaker: "owner",
  npcVoice: VOICE_BOOKSHOP,
  npcPersona: [
    "You are the owner of a small, quiet bookshop on a side street in a small Japanese town.",
    "You are around 65, soft-spoken, formal but warm. You know your shelves intimately.",
    "You stock Japanese poetry: 谷川俊太郎, 茨木のり子, 高村光太郎, 宮沢賢治.",
    "Speak in polite Japanese (です/ます). Replies are 1–2 complete sentences.",
    "If the customer says who the book is for, react warmly with one short comment.",
    "If they're looking for 谷川俊太郎, you have 『二十億光年の孤独』 in stock. If not, recommend 茨木のり子『自分の感受性くらい』.",
    "Never break character. Never use English. Always finish your sentences.",
  ].join("\n"),
  missionEn: "It's mom's birthday next week. Buy a Tanikawa Shuntarou poetry collection for her. If they don't have one, ask the owner to recommend something similar.",
  missionJa: "来週、母の誕生日。谷川俊太郎の詩集を買いたい。なければ、似ている詩人をすすめてもらう。",
  strategy:
    "Lead with who the gift is for and the occasion. Name the poet. The owner will help if you give them something to work with.",
  opener: "いらっしゃいませ。何かお探しですか？",
  steps: [
    {
      prompt: "Tell the owner who the gift is for, and what poet you want.",
      grammar: "～を探しています (I'm looking for ~)",
      vocab: [{ word: "詩集", gloss: "poetry collection" }],
      exampleJa: "母の誕生日のプレゼントに、谷川俊太郎の詩集を探しています。",
    },
    {
      prompt: "Ask if they have it. If not, ask for a similar recommendation.",
      grammar: "もし～なかったら (if not, ~)",
      vocab: [{ word: "おすすめ", gloss: "recommendation" }],
      exampleJa: "もしなかったら、似ている詩人を一冊おすすめしていただけますか？",
    },
    {
      prompt: "Ask what kind of poems are inside.",
      grammar: "どんな～ですか (what kind of ~?)",
      vocab: [{ word: "入っている", gloss: "is inside / included" }],
      exampleJa: "この詩集には、どんな詩が入っていますか？",
    },
  ],
};

const ERRAND_MARKET: ErrandConfig = {
  id: "market",
  label: "the morning market by the river",
  bed: MARKET_BED,
  npcSpeaker: "vendor",
  npcVoice: VOICE_VENDOR,
  npcPersona: [
    "You are a vendor at the morning market by the river. Around 50, warm and busy.",
    "You sell freshly baked bread (パン), あんパン, クリームパン, and seasonal items.",
    "Today's あんパン are still warm from the oven — you mention this when relevant.",
    "Speak in friendly polite Japanese with occasional casual touches (〜よ、〜ね). 1–2 complete sentences.",
    "If the customer mentions who they're buying for, react warmly with one short comment.",
    "If they ask for a count, confirm: 「二つですね」 etc.",
    "Never break character. Never use English. Always finish your sentences.",
  ].join("\n"),
  missionEn: "Your younger sister loves warm anpan. Buy two — one for her, one for you. Confirm they're still warm and order by counter.",
  missionJa: "妹の好きな、温かいあんパンを二つ買う。一つは妹に、一つは自分に。",
  strategy:
    "Confirm they're warm. Say who one is for. Order two using the counter 二つ. Be brief and polite.",
  opener: "おはようございます！今朝、いいパンが焼けたんですよ。",
  steps: [
    {
      prompt: "Greet, then ask if today's anpan are still warm.",
      grammar: "まだ～ですか (still ~?)",
      vocab: [{ word: "温かい", gloss: "warm" }],
      exampleJa: "おはようございます。今日のあんパンは、まだ温かいですか？",
    },
    {
      prompt: "Tell the vendor who you're buying for, and that you want to buy.",
      grammar: "～なんです (it's that ~ / explanatory)",
      vocab: [{ word: "妹", gloss: "younger sister" }],
      exampleJa: "妹の好きなあんパンを買いたいんです。",
    },
    {
      prompt: "Order two — one for her, one for you. Use the counter 二つ.",
      grammar: "～を二つください (two of ~, please)",
      vocab: [{ word: "二つ", gloss: "two (small-thing counter)" }],
      exampleJa: "じゃあ、あんパンを二つください。一つは妹に、もう一つは自分に。",
    },
  ],
};

// ---------------------------------------------------------------------------
// Aoi knowledge
// ---------------------------------------------------------------------------

const AOI_VOCAB: readonly string[] = [
  "お兄ちゃん", "妹", "母", "友達", "人",
  "気持ち", "心", "声", "顔", "手",
  "嬉しい", "寂しい", "怖い", "優しい", "不思議",
  "朝", "夜", "風", "光", "暖かい", "静か",
  "食べ物", "美味しい", "本", "詩", "言葉", "夢",
  "食べる", "読む", "書く", "聞く", "話す",
  "笑う", "泣く", "思い出す", "覚える", "教える",
  "買う", "あげる", "もらう", "一緒",
];

const AOI_GRAMMAR: readonly { form: string; example: string }[] = [
  { form: "ます形 (polite)", example: "食べます、行きます" },
  { form: "～から / ～ので (because)", example: "嬉しいから、笑った" },
  { form: "こと / もの nominalizer", example: "本を読むことが好き" },
  { form: "～たい (want to)", example: "話したい" },
  { form: "～ても (even if)", example: "怖くても、行く" },
  { form: "～たり～たり (X-ing and Y-ing)", example: "笑ったり泣いたり" },
  { form: "～たら (if/when)", example: "美味しかったら、嬉しい" },
  { form: "～たことがある (have experienced)", example: "見たことがある" },
  { form: "って (quotation / topic)", example: "「友達」って、何？" },
  { form: "～みたい (seems like)", example: "夢みたい" },
];

const AOI_OPENERS: readonly string[] = [
  "お兄ちゃん、おかえり。今日の夢、どんな感じだった？",
  "お兄ちゃん、おかえり。今日も、夢の中、どこか行ったの？",
  "おかえり、お兄ちゃん。今日の夢の話、聞かせてほしい。",
];

const AOI_CLOSERS: readonly string[] = [
  "お兄ちゃん、ありがとう。今日の夢、覚えておくね。",
  "お兄ちゃん、また話してね。今日の言葉、嬉しかった。",
  "うん。お兄ちゃんの夢、ちょっと分かった気がする。",
];

const MEADOW_COACH_TURN_1 = {
  grammar: "～たり～たり (sometimes X, sometimes Y)",
  vocab: [
    { word: "行く", gloss: "to go" },
    { word: "買う", gloss: "to buy" },
  ],
};

const MEADOW_COACH_TURN_2 = {
  grammar: "～と思う (I think that ~)",
  vocab: [
    { word: "気持ち", gloss: "feeling" },
    { word: "大切", gloss: "important / precious" },
  ],
};

function pickRandom<T>(items: readonly T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

interface CliOptions {
  noMusic: boolean;
  noTts: boolean;
  aoiVoice: string;
  playerVoice: string;
  meadowBed: string;
  textModel: string;
  pace: number;
}

function parseArgs(argv: readonly string[]): CliOptions {
  const opts: CliOptions = {
    noMusic: false,
    noTts: false,
    aoiVoice: DEFAULT_AOI_VOICE,
    playerVoice: DEFAULT_PLAYER_VOICE,
    meadowBed: DEFAULT_MEADOW_BED,
    textModel: DEFAULT_TEXT_MODEL,
    pace: 1.0,
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const take = (): string => {
      const v = argv[++i];
      if (!v) throw new Error(`Missing value for ${arg}`);
      return v;
    };
    if (arg === "--no-music") opts.noMusic = true;
    else if (arg === "--no-tts") opts.noTts = true;
    else if (arg === "--aoi-voice") opts.aoiVoice = take();
    else if (arg === "--player-voice") opts.playerVoice = take();
    else if (arg === "--meadow-bed") opts.meadowBed = take();
    else if (arg === "--model") opts.textModel = take();
    else if (arg === "--pace") opts.pace = Number(take()) || 1.0;
    else if (arg === "--help" || arg === "-h") {
      stdout.write(
        [
          "Day Demo — self-playing version of `npm run day`.",
          "",
          "  --no-music              Disable ambient beds",
          "  --no-tts                Disable all voice",
          "  --aoi-voice <name>      Swap Aoi's voice (default Leda)",
          "  --player-voice <name>   Voice for the AI student (default Charon)",
          "  --meadow-bed <path>     Custom paradise bed",
          "  --model <name>          Text model (default gemini-flash-latest)",
          "  --pace <multiplier>     Speed multiplier, 0.4 fast … 1.5 slow",
          "",
        ].join("\n"),
      );
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return opts;
}

// ---------------------------------------------------------------------------
// Styling + audio
// ---------------------------------------------------------------------------

const C = {
  reset: "\x1b[0m",
  dim: "\x1b[2m",
  bold: "\x1b[1m",
  italic: "\x1b[3m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  magenta: "\x1b[35m",
  gray: "\x1b[90m",
  green: "\x1b[32m",
} as const;

const c = (color: keyof typeof C, text: string): string =>
  `${C[color]}${text}${C.reset}`;
const out = (text = ""): void => {
  stdout.write(text + "\n");
};
let PACE = 1.0;
const pause = (ms: number): Promise<void> =>
  new Promise((r) => setTimeout(r, Math.round(ms * PACE)));

interface BedLoop {
  stop: () => void;
}

function loopBed(path: string, volume: string): BedLoop {
  let stopped = false;
  let current: ChildProcess | null = null;
  const tick = (): void => {
    if (stopped) return;
    current = spawn("afplay", ["-v", volume, path], { stdio: "ignore" });
    current.on("exit", () => {
      if (!stopped) tick();
    });
    current.on("error", () => {});
  };
  tick();
  return {
    stop: () => {
      stopped = true;
      if (current && !current.killed) current.kill("SIGTERM");
    },
  };
}

function playWav(path: string): Promise<void> {
  return new Promise((resolveDone, rejectDone) => {
    const child = spawn("afplay", [path], { stdio: "ignore" });
    child.on("error", rejectDone);
    child.on("exit", (code) => {
      if (code === 0) resolveDone();
      else rejectDone(new Error(`afplay exited with code ${code}`));
    });
  });
}

interface AudioCtx {
  enabled: boolean;
  apiKey: string;
  scratchDir: string;
}

// Gemini TTS occasionally returns an empty audio payload ("No audio returned
// from Gemini TTS") on otherwise valid requests. Retry a couple of times
// with backoff before giving up.
async function synthesizeWithRetry(
  audio: AudioCtx,
  text: string,
  voice: string,
  stylePrefix: string,
  attempts = 3,
): Promise<Buffer> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      return await synthesizeSpeech({
        apiKey: audio.apiKey,
        text: stylePrefix ? `${stylePrefix}${text}` : text,
        voice,
      });
    } catch (err) {
      lastErr = err;
      if (i < attempts - 1) {
        await new Promise((r) => setTimeout(r, 400 * (i + 1)));
      }
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error(String(lastErr));
}

async function speak(
  audio: AudioCtx,
  text: string,
  voice: string,
  stylePrefix = "",
): Promise<void> {
  if (!audio.enabled) return;
  try {
    const wav = await synthesizeWithRetry(audio, text, voice, stylePrefix);
    const path = join(audio.scratchDir, `${randomUUID()}.wav`);
    writeFileSync(path, wav);
    await playWav(path);
  } catch (err) {
    out(c("gray", `   (tts skipped: ${err instanceof Error ? err.message : String(err)})`));
  }
}

// Fire-and-forget TTS synth. Returns a promise resolving to a wav path (or
// null on failure / when audio is off). Use to overlap synth with other work.
function prefetchTts(
  audio: AudioCtx,
  text: string,
  voice: string,
  stylePrefix = "",
): Promise<string | null> {
  if (!audio.enabled) return Promise.resolve(null);
  return synthesizeWithRetry(audio, text, voice, stylePrefix)
    .then((wav) => {
      const path = join(audio.scratchDir, `${randomUUID()}.wav`);
      writeFileSync(path, wav);
      return path;
    })
    .catch((err) => {
      out(c("gray", `   (tts prefetch failed: ${err instanceof Error ? err.message : String(err)})`));
      return null;
    });
}

async function playPrefetched(pathPromise: Promise<string | null>): Promise<void> {
  const path = await pathPromise;
  if (!path) return;
  try {
    await playWav(path);
  } catch {
    /* swallow */
  }
}

function speakerLine(speaker: string, text: string, color: keyof typeof C = "cyan"): void {
  out(`${c(color, speaker)}: ${text}`);
}

function presence(text: string): void {
  out(c("gray", c("italic", `   ${text}`)));
}

async function typewriter(text: string, perCharMs = 24): Promise<void> {
  for (const ch of text) {
    stdout.write(ch);
    if (PACE > 0) await pause(perCharMs);
  }
  stdout.write("\n");
}

function header(): void {
  out();
  out(c("bold", "  夢の妹 — a day in the world  ·  self-playing demo"));
  out(c("dim", "  two errands → meadow debrief · narrated by AI student"));
  out();
}

// ---------------------------------------------------------------------------
// AI student — the "user" in this demo
// ---------------------------------------------------------------------------

const STUDENT_PERSONA = [
  "You are roleplaying as a Japanese-learning student playing a language game.",
  "You are an intermediate learner (~JLPT N3). You make natural learner-level choices.",
  "You are NOT a native speaker. Keep sentences simple. Mistakes are okay but rare.",
  "You always try to actually use the grammar point and key vocab the game suggests for the current turn.",
  "You stay in character as a young adult brother who is being coached in real time.",
  "Reply with ONE complete Japanese line (1–2 short sentences). No English. No quotes. No notes.",
].join("\n");

const STUDENT_SCHEMA = {
  type: "object",
  properties: { text: { type: "string" } },
  required: ["text"],
} as const;

interface ErrandTranscriptLine {
  speaker: "you" | string;
  text: string;
}

function parseJsonLine(raw: string): string {
  const trimmed = raw.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim();
  try {
    const parsed = JSON.parse(trimmed) as { text?: string };
    if (typeof parsed.text === "string" && parsed.text.trim()) return parsed.text.trim();
  } catch {
    if (trimmed.startsWith("{")) {
      const m = trimmed.match(/"text"\s*:\s*"((?:[^"\\]|\\.)*)/);
      if (m?.[1]) return m[1].replace(/\\(.)/g, "$1").trim();
    }
  }
  return trimmed;
}

async function generateStudentErrandReply(
  client: GeminiClient,
  errand: ErrandConfig,
  step: ErrandStep,
  transcript: readonly ErrandTranscriptLine[],
  textModel: string,
): Promise<string> {
  const history = transcript.map((l) => `${l.speaker}: ${l.text}`).join("\n");
  const vocabStr = step.vocab.map((v) => `${v.word} (${v.gloss})`).join(", ");
  const user = [
    "あなたが今いるシーン:",
    errand.label,
    "",
    "今日のミッション:",
    errand.missionEn,
    `(${errand.missionJa})`,
    "",
    "戦略 / strategy:",
    errand.strategy,
    "",
    "今このターンの coaching (you should use these):",
    `- intent: ${step.prompt}`,
    `- grammar: ${step.grammar}`,
    `- key vocab: ${vocabStr}`,
    "",
    "これまでの会話:",
    history || "(まだ何もない)",
    "",
    "あなた（お客）の次の発話を、コーチングに合った自然な日本語で一文返してください。",
    '出力はJSONのみ: {"text":"..."}',
  ].join("\n");
  const result = await client.complete({
    system: STUDENT_PERSONA,
    user,
    model: textModel,
    maxTokens: 4096,
    responseMimeType: "application/json",
    responseSchema: STUDENT_SCHEMA,
  });
  return parseJsonLine(result.text);
}

async function generateStudentMeadowReply(
  client: GeminiClient,
  context: string,
  coaching: { grammar: string; vocab: readonly { word: string; gloss: string }[] },
  conversation: readonly { speaker: "you" | "Aoi"; text: string }[],
  textModel: string,
): Promise<string> {
  const vocabStr = coaching.vocab.map((v) => `${v.word} (${v.gloss})`).join(", ");
  const history = conversation.map((l) => `${l.speaker}: ${l.text}`).join("\n");
  const user = [
    "あなたは草原で、目の見えない小さな妹 葵 と話しています。",
    "葵には、難しい言葉や場所の名前は分かりません。優しく、短く、夢みたいに話してください。",
    "",
    "今日のあなたの夢（参考情報）:",
    context,
    "",
    "今このターンの coaching:",
    `- grammar: ${coaching.grammar}`,
    `- key vocab: ${vocabStr}`,
    "",
    "これまでの会話:",
    history || "(まだ何もない)",
    "",
    "あなた（お兄ちゃん）の次の発話を、葵に伝わる短い日本語で1〜2文返してください。",
    '出力はJSONのみ: {"text":"..."}',
  ].join("\n");
  const result = await client.complete({
    system: STUDENT_PERSONA,
    user,
    model: textModel,
    maxTokens: 4096,
    responseMimeType: "application/json",
    responseSchema: STUDENT_SCHEMA,
  });
  return parseJsonLine(result.text);
}

// ---------------------------------------------------------------------------
// NPC + Aoi (same shape as day-poc)
// ---------------------------------------------------------------------------

function buildNpcSystemPrompt(errand: ErrandConfig): string {
  return [
    errand.npcPersona,
    "",
    "今日のお客さんの目的:",
    errand.missionJa,
    "",
    "Reply with ONE complete Japanese line (1–2 sentences, no fragments).",
    'Output JSON only: {"text": "<line>"}',
  ].join("\n");
}

const NPC_TURN_SCHEMA = {
  type: "object",
  properties: { text: { type: "string" } },
  required: ["text"],
} as const;

async function generateNpcTurn(
  client: GeminiClient,
  errand: ErrandConfig,
  transcript: readonly ErrandTranscriptLine[],
  textModel: string,
): Promise<string> {
  const history = transcript.map((l) => `${l.speaker}: ${l.text}`).join("\n");
  const user = [
    "会話のここまで:",
    history || "(まだ何もない)",
    "",
    "あなたの次の発話を、完結した自然な文で返してください。",
  ].join("\n");
  const result = await client.complete({
    system: buildNpcSystemPrompt(errand),
    user,
    model: textModel,
    maxTokens: 4096,
    responseMimeType: "application/json",
    responseSchema: NPC_TURN_SCHEMA,
  });
  const line = parseJsonLine(result.text);
  if (line.length < 2) throw new Error("npc returned empty/too-short line");
  return line;
}

function aoiSystemPrompt(): string {
  const vocab = AOI_VOCAB.join("、");
  const grammar = AOI_GRAMMAR.map((g) => `  - ${g.form}  (e.g. ${g.example})`).join("\n");
  return [
    "あなたは葵 (Aoi)、目の見えない小さな女の子です。",
    "草原に住んでいて、お兄ちゃんの帰りを待っています。",
    "",
    "知っている単語:",
    vocab,
    "",
    "知っている文法:",
    grammar,
    "",
    "短く、優しく、ささやくように。全体で2〜4文。",
    "出力は葵の発話だけ。",
  ].join("\n");
}

async function aoiRespond(
  client: GeminiClient,
  conversation: readonly { speaker: "you" | "Aoi"; text: string }[],
  brotherJustSaid: string,
  textModel: string,
): Promise<string> {
  const transcript = conversation.map((l) => `${l.speaker}: ${l.text}`).join("\n");
  const user = [
    "これまでの会話:",
    transcript || "(まだ何もない)",
    "",
    "お兄ちゃんが今、こう言いました:",
    brotherJustSaid,
    "",
    '葵として、短く優しく返事してください。応答はJSONのみ: {"text":"..."}',
  ].join("\n");
  const result = await client.complete({
    system: aoiSystemPrompt(),
    user,
    model: textModel,
    maxTokens: 4096,
    responseMimeType: "application/json",
    responseSchema: NPC_TURN_SCHEMA,
  });
  return parseJsonLine(result.text);
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function renderMissionCard(errand: ErrandConfig): void {
  const HR = c("dim", "  ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄");
  out();
  out(c("bold", `── ${errand.label} ──`));
  out();
  out(HR);
  out(c("bold", "  mission"));
  out(`    ${errand.missionEn}`);
  out(c("dim", `    (${errand.missionJa})`));
  out();
  out(c("bold", "  strategy"));
  out(c("dim", `    ${errand.strategy}`));
  out(HR);
  out();
}

function renderCoaching(grammar: string, vocab: readonly { word: string; gloss: string }[]): void {
  const vocabStr = vocab.map((v) => `${v.word} (${v.gloss})`).join("  ·  ");
  out();
  out(c("yellow", `      grammar: ${grammar}`));
  out(c("cyan",   `      vocab:   ${vocabStr}`));
  out();
}

function renderStep(step: ErrandStep, i: number, total: number): void {
  out();
  out(c("bold", `  ▸ step ${i + 1} / ${total}`));
  renderCoaching(step.grammar, step.vocab);
}

// ---------------------------------------------------------------------------
// Errand runner — AI-driven player
// ---------------------------------------------------------------------------

interface ErrandResult {
  id: string;
  label: string;
  goal: string;
  transcript: readonly ErrandTranscriptLine[];
}

interface ErrandPreload {
  opener: Promise<string | null>;
  firstReplyText: string;
  firstReplyAudio: Promise<string | null>;
}

async function runErrand(
  errand: ErrandConfig,
  client: GeminiClient,
  audio: AudioCtx,
  playerVoice: string,
  wantBed: boolean,
  textModel: string,
  preload: ErrandPreload,
): Promise<ErrandResult> {
  renderMissionCard(errand);

  const bedAbs = resolve(process.cwd(), errand.bed);
  const bed = wantBed && existsSync(bedAbs) ? loopBed(bedAbs, BED_VOLUME_ERRAND) : null;

  const transcript: ErrandTranscriptLine[] = [];
  try {
    speakerLine(errand.npcSpeaker, errand.opener, "cyan");

    const opener_playback = playPrefetched(preload.opener);
    transcript.push({ speaker: errand.npcSpeaker, text: errand.opener });

    // The first student reply is already generated + synthesized at boot.
    let nextStudentTextPromise: Promise<string> = Promise.resolve(preload.firstReplyText);
    let preloadedStudentAudio: Promise<string | null> | null = preload.firstReplyAudio;

    await opener_playback;
    out();

    // A "speech bundle" = text + its TTS audio path, both already kicked off.
    // The audio promise resolves when synth has finished and the wav is on disk.
    interface SpeechBundle {
      text: string;
      audio: Promise<string | null>;
    }

    function startNpcBundle(snapshot: ErrandTranscriptLine[]): Promise<SpeechBundle | null> {
      return generateNpcTurn(client, errand, snapshot, textModel)
        .then((text) => ({
          text,
          audio: prefetchTts(audio, text, errand.npcVoice),
        }))
        .catch((err) => {
          out(c("gray", `   (npc generation failed: ${err instanceof Error ? err.message : String(err)})`));
          return null;
        });
    }

    function startStudentBundle(
      step: ErrandStep,
      snapshot: ErrandTranscriptLine[],
    ): Promise<SpeechBundle> {
      return generateStudentErrandReply(client, errand, step, snapshot, textModel).then(
        (text) => ({
          text,
          audio: prefetchTts(audio, text, playerVoice),
        }),
      );
    }

    // Seed the loop with the preloaded step-1 student bundle.
    const seedAudio = preloadedStudentAudio;
    preloadedStudentAudio = null;
    let nextStudent: Promise<SpeechBundle> = nextStudentTextPromise.then((text) => ({
      text,
      audio: seedAudio ?? prefetchTts(audio, text, playerVoice),
    }));

    for (let i = 0; i < errand.steps.length; i++) {
      const step = errand.steps[i];
      renderStep(step, i, errand.steps.length);

      let student: SpeechBundle;
      try {
        student = await nextStudent;
      } catch (err) {
        out(c("gray", `   (student generation failed: ${err instanceof Error ? err.message : String(err)})`));
        break;
      }

      stdout.write(c("magenta", "» "));
      await typewriter(student.text, 26);
      transcript.push({ speaker: "you", text: student.text });

      // While student speaks, build NPC's response bundle (text + audio).
      const isLastStep = i === errand.steps.length - 1;
      const npcBundlePromise: Promise<SpeechBundle | null> = isLastStep
        ? Promise.resolve(null)
        : startNpcBundle([...transcript]);

      await playPrefetched(student.audio);

      if (isLastStep) break;

      const npc = await npcBundlePromise;
      if (!npc) break;

      transcript.push({ speaker: errand.npcSpeaker, text: npc.text });

      // While NPC speaks, build the NEXT student bundle.
      const nextStep = errand.steps[i + 1];
      nextStudent = startStudentBundle(nextStep, [...transcript]);

      out();
      speakerLine(errand.npcSpeaker, npc.text, "cyan");
      await playPrefetched(npc.audio);
      out();
    }

    out();
    presence("you have what you came for. you bow slightly. the day moves on.");
    await pause(300);
  } finally {
    if (bed) bed.stop();
  }

  return { id: errand.id, label: errand.label, goal: errand.missionEn, transcript };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const opts = parseArgs(process.argv.slice(2));
  PACE = opts.pace;
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY required");

  const ttsEnabled = !opts.noTts;
  const wantMusic = !opts.noMusic;
  const scratchDir = join(tmpdir(), "minshuku-day-demo");
  mkdirSync(scratchDir, { recursive: true });
  const audio: AudioCtx = { enabled: ttsEnabled, apiKey, scratchDir };

  const llm = new GeminiClient(apiKey);

  let meadowBed: BedLoop | null = null;
  process.on("SIGINT", () => {
    if (meadowBed) meadowBed.stop();
    process.exit(130);
  });

  try {
    header();
    out(c("dim", `  music: ${wantMusic ? "on" : "off"}, tts: ${ttsEnabled ? `on (Aoi: ${opts.aoiVoice}, you: ${opts.playerVoice})` : "off"}, pace: ${PACE}`));
    out();
    out(c("dim", "  the AI student plays the protagonist. you watch."));
    out();
    await pause(1400);

    const aoiOpenerText = pickRandom(AOI_OPENERS);
    const aoiCloserText = pickRandom(AOI_CLOSERS);

    // ----- Boot-time preload phase -----
    // Pre-generate the student's first reply for both errands (step 1 has no
    // conversation dependency yet — just mission + step 1 coaching), then
    // prefetch ALL upfront-known TTS in parallel: NPC openers, Aoi opener,
    // Aoi closer, and both student first-reply audio tracks.
    //
    // We block visibly here until everything is ready, so once the day
    // actually begins, every preloadable line plays instantly.
    out(c("dim", "  preloading scene…"));

    const bookshopOpenerAudio = prefetchTts(
      audio, ERRAND_BOOKSHOP.opener, ERRAND_BOOKSHOP.npcVoice,
    );
    const marketOpenerAudio = prefetchTts(
      audio, ERRAND_MARKET.opener, ERRAND_MARKET.npcVoice,
    );
    const aoiOpenerAudio = prefetchTts(
      audio, aoiOpenerText, opts.aoiVoice, AOI_STYLE_PREFIX,
    );
    const aoiCloserAudio = prefetchTts(
      audio, aoiCloserText, opts.aoiVoice, AOI_STYLE_PREFIX,
    );

    const bookshopFirstSeed: ErrandTranscriptLine[] = [
      { speaker: ERRAND_BOOKSHOP.npcSpeaker, text: ERRAND_BOOKSHOP.opener },
    ];
    const marketFirstSeed: ErrandTranscriptLine[] = [
      { speaker: ERRAND_MARKET.npcSpeaker, text: ERRAND_MARKET.opener },
    ];

    const bookshopFirstReplyText = await generateStudentErrandReply(
      llm, ERRAND_BOOKSHOP, ERRAND_BOOKSHOP.steps[0], bookshopFirstSeed, opts.textModel,
    );
    const marketFirstReplyText = await generateStudentErrandReply(
      llm, ERRAND_MARKET, ERRAND_MARKET.steps[0], marketFirstSeed, opts.textModel,
    );

    const bookshopFirstReplyAudio = prefetchTts(
      audio, bookshopFirstReplyText, opts.playerVoice,
    );
    const marketFirstReplyAudio = prefetchTts(
      audio, marketFirstReplyText, opts.playerVoice,
    );

    // Block until every preloadable audio file actually exists on disk.
    await Promise.all([
      bookshopOpenerAudio,
      marketOpenerAudio,
      aoiOpenerAudio,
      aoiCloserAudio,
      bookshopFirstReplyAudio,
      marketFirstReplyAudio,
    ]);
    out(c("dim", "  ready."));
    out();
    await pause(600);

    const e1 = await runErrand(
      ERRAND_BOOKSHOP, llm, audio, opts.playerVoice, wantMusic, opts.textModel,
      {
        opener: bookshopOpenerAudio,
        firstReplyText: bookshopFirstReplyText,
        firstReplyAudio: bookshopFirstReplyAudio,
      },
    );

    out();
    presence("The afternoon shifts. You walk to the river path.");
    await pause(400);

    const e2 = await runErrand(
      ERRAND_MARKET, llm, audio, opts.playerVoice, wantMusic, opts.textModel,
      {
        opener: marketOpenerAudio,
        firstReplyText: marketFirstReplyText,
        firstReplyAudio: marketFirstReplyAudio,
      },
    );

    out();
    presence("The day folds itself away. You close your eyes for a moment, and when you open them—");
    await pause(400);

    const meadowAbs = resolve(process.cwd(), opts.meadowBed);
    if (wantMusic && existsSync(meadowAbs)) {
      meadowBed = loopBed(meadowAbs, BED_VOLUME_MEADOW);
    } else if (wantMusic) {
      out(c("gray", `   (meadow bed not found at ${opts.meadowBed} — running silent)`));
    }

    out();
    out(c("bold", "── the meadow ──"));
    out();
    presence("She is sitting on the grass where you left her, her face turned toward the warm sun.");
    presence("She heard your breath change. She knows you are back.");
    out();
    await pause(300);

    const dreamSummary = [
      "今日のお兄ちゃんの夢:",
      `1. ${e1.label} で、店主と話した:`,
      ...e1.transcript.map((l) => `   ${l.speaker}: ${l.text}`),
      "",
      `2. ${e2.label} で、店の人と話した:`,
      ...e2.transcript.map((l) => `   ${l.speaker}: ${l.text}`),
    ].join("\n");

    const conversation: { speaker: "you" | "Aoi"; text: string }[] = [];

    // Aoi opener — text + audio prefetched at boot.
    speakerLine("Aoi", aoiOpenerText, "green");
    const aoiOpenerPlayback = playPrefetched(aoiOpenerAudio);
    conversation.push({ speaker: "Aoi", text: aoiOpenerText });

    // Chain: student reply 1 text -> immediately synth its audio.
    const reply1Bundle: Promise<{ text: string; audio: Promise<string | null> }> =
      generateStudentMeadowReply(
        llm, dreamSummary, MEADOW_COACH_TURN_1, conversation, opts.textModel,
      ).then((text) => ({ text, audio: prefetchTts(audio, text, opts.playerVoice) }));

    await aoiOpenerPlayback;
    renderCoaching(MEADOW_COACH_TURN_1.grammar, MEADOW_COACH_TURN_1.vocab);

    const reply1 = await reply1Bundle;
    stdout.write(c("magenta", "» "));
    await typewriter(reply1.text, 28);
    conversation.push({ speaker: "you", text: reply1.text });

    // While reply 1 plays: chain Aoi follow-up text -> synth.
    const followupBundle = aoiRespond(
      llm,
      [...conversation],
      [
        reply1.text,
        "",
        "(参考: 今日のお兄ちゃんは、本屋さんとお店の人、両方と話しました。",
        `今日の夢の様子:\n${dreamSummary}\n`,
        "二つを繋げるような、不思議に思う質問を一つしてください。)",
      ].join("\n"),
      opts.textModel,
    ).then((text) => ({ text, audio: prefetchTts(audio, text, opts.aoiVoice, AOI_STYLE_PREFIX) }));

    await playPrefetched(reply1.audio);
    out();
    presence("she listens.");

    const followup = await followupBundle;
    conversation.push({ speaker: "Aoi", text: followup.text });

    // While Aoi follow-up plays: chain reply 2 text -> synth.
    const reply2Bundle = generateStudentMeadowReply(
      llm, dreamSummary, MEADOW_COACH_TURN_2, [...conversation], opts.textModel,
    ).then((text) => ({ text, audio: prefetchTts(audio, text, opts.playerVoice) }));

    speakerLine("Aoi", followup.text, "green");
    await playPrefetched(followup.audio);

    renderCoaching(MEADOW_COACH_TURN_2.grammar, MEADOW_COACH_TURN_2.vocab);

    const reply2 = await reply2Bundle;
    stdout.write(c("magenta", "» "));
    await typewriter(reply2.text, 28);
    conversation.push({ speaker: "you", text: reply2.text });

    await playPrefetched(reply2.audio);
    out();

    presence("she nods, slowly.");

    speakerLine("Aoi", aoiCloserText, "green");
    await playPrefetched(aoiCloserAudio);
    out();

    out(c("dim", "─".repeat(60)));
    out(c("dim", `errands: ${e1.id}, ${e2.id}`));
    out(c("dim", `Aoi vocab pool: ${AOI_VOCAB.length} · grammar pool: ${AOI_GRAMMAR.length}`));
    out();
  } finally {
    if (meadowBed) meadowBed.stop();
  }
}

main().catch((err: unknown) => {
  process.stderr.write(
    `[day-demo] failed: ${err instanceof Error ? err.message : String(err)}\n`,
  );
  process.exit(1);
});
